AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Infraestrutura compartilhada para microsserviços de feedbacks

Resources:

  ## =========================
  ## DynamoDB - Feedbacks
  ## =========================
  FeedbackTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: FeedbackTable
      PrimaryKey:
        Name: id
        Type: String
      Tags:
        Project: FeedbackPlatform

  ## =========================
  ## SQS - Fila de Urgência
  ## =========================
  FilaUrgencia:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: FilaUrgencia
      VisibilityTimeout: 30
      MessageRetentionPeriod: 345600
      Tags:
        - Key: Project
          Value: FeedbackPlatform

  ## =========================
  ## SNS - Tópico de Urgência
  ## =========================
  UrgencyTopic:
     Type: AWS::SNS::Topic
     Properties:
       TopicName: Urgencia

  ## =========================
  ## SNS - Tópico de Relatórios
  ## =========================
  ReportTopic:
     Type: AWS::SNS::Topic
     Properties:
       TopicName: Relatorios

  ## =========================
  ## SNS - Tópico de Inscritos para receber Relatórios
  ## =========================
  ReportSubscriptionTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: InscritosRelatorios

  ## =========================
  ## S3 - Bucket de Relatórios
  ## =========================
  ReportBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: fiap-feedback-report-s3
      Tags:
        - Key: Project
          Value: FeedbackPlatform

Outputs:

  ## -------------------------
  ## DynamoDB - Feedbacks - Export
  ## -------------------------
  FeedbackTableName: # Para MS1 e MS3: acessar tabela para read/write
    Description: Nome da tabela DynamoDB Feedbacks
    Value: !Ref FeedbackTable
    Export:
      Name: FeedbackTableName

  ## -------------------------
  ## SQS - Fila de Urgência - Export
  ## -------------------------
  FilaUrgenciaArn: # Para configurar o trigger do Lambda no MS2
    Description: ARN da fila de urgência
    Value: !GetAtt FilaUrgencia.Arn
    Export:
      Name: FilaUrgenciaArn

  ## =========================
  ## SNS - Tópico de Urgência - Export
  ## =========================
  UrgencyTopicArn:
    Description: "ARN do Tópico SNS de Urgência"
    Value: !Ref UrgencyTopic
    Export:
      Name: UrgencyTopicArn

  ## =========================
  ## SNS - Tópico de Relatórios - Export
  ## =========================
  ReportTopicArn:
    Description: "ARN do Tópico SNS de Relatórios"
    Value: !Ref ReportTopic
    Export:
      Name: ReportTopicArn

  ## =========================
  ## SNS - Tópico de Incritos Relatórios - Export
  ## =========================
  ReportSubscriptionTopicArn:
    Description: "ARN do Tópico SNS de Incritos no Relatórios"
    Value: !Ref ReportSubscriptionTopic
    Export:
      Name: ReportSubscriptionTopicArn

  ## =========================
  ## S3 - Bucket de Relatórios - Export
  ## =========================
  ReportBucketName:
    Description: "Nome do Bucket S3 de Relatórios"
    Value: !Ref ReportBucket
    Export:
      Name: ReportBucketName
