AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Infraestrutura compartilhada para microsserviços de feedbacks

Resources:

  ## =========================
  ## DynamoDB - Feedbacks
  ## =========================
  FeedbackTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: FeedbackTable
      PrimaryKey:
        Name: id
        Type: String
      Tags:
        Project: FeedbackPlatform

  ## =========================
  ## DynamoDB - Admins
  ## =========================
  AdminTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: AdminTable
      PrimaryKey:
        Name: email
        Type: String
      Tags:
        Project: FeedbackPlatform

  ## =========================
  ## SQS - Fila de Urgência
  ## =========================
  FilaUrgencia:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: FilaUrgencia
      VisibilityTimeout: 30
      MessageRetentionPeriod: 345600
      Tags:
        - Key: Project
          Value: FeedbackPlatform

  ## =========================
  ## SNS - Tópico de Relatórios
  ## =========================
  ReportTopic:
     Type: AWS::SNS::Topic
     Properties:
       TopicName: Relatorios

  ## =========================
  ## S3 - Bucket de Relatórios
  ## =========================
  ReportBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: fiap-feedback-report-s3-manu
      Tags:
        - Key: Project
          Value: FeedbackPlatform

Outputs:

  ## -------------------------
  ## DynamoDB - Feedbacks - Export
  ## -------------------------
  FeedbackTableName:
    Description: Nome da tabela DynamoDB Feedbacks
    Value: !Ref FeedbackTable
    Export:
      Name: FeedbackTableName

  FeedbackTableArn:
    Description: ARN da tabela DynamoDB Feedbacks
    Value: !GetAtt FeedbackTable.Arn
    Export:
      Name: FeedbackTableArn

  ## -------------------------
  ## DynamoDB - Admins - Export
  ## -------------------------
  AdminTableName:
    Description: Nome da tabela DynamoDB Admins
    Value: !Ref AdminTable
    Export:
      Name: AdminTableName

  AdminTableArn:
    Description: ARN da tabela DynamoDB Admins
    Value: !GetAtt AdminTable.Arn
    Export:
      Name: AdminTableArn

  ## -------------------------
  ## SQS - Fila de Urgência - Export
  ## -------------------------
  FilaUrgenciaArn:
    Description: ARN da fila de urgência
    Value: !GetAtt FilaUrgencia.Arn
    Export:
      Name: FilaUrgenciaArn

  FilaUrgenciaQueueUrl:
    Description: URL da fila de urgência
    Value: !Ref FilaUrgencia
    Export:
      Name: FilaUrgenciaQueueUrl

  FilaUrgenciaQueueName:
    Description: Nome da fila de urgência
    Value: !GetAtt FilaUrgencia.QueueName
    Export:
      Name: FilaUrgenciaQueueName

  ## =========================
  ## SNS - Tópico de Relatórios - Export
  ## =========================
  ReportTopicArn:
    Description: "ARN do Tópico SNS de Relatórios"
    Value: !Ref ReportTopic
    Export:
      Name: ReportTopicArn

  ## =========================
  ## S3 - Bucket de Relatórios - Export
  ## =========================
  ReportBucketName:
    Description: "Nome do Bucket S3 de Relatórios"
    Value: !Ref ReportBucket
    Export:
      Name: ReportBucketName
